### ISSUE TITLE
dat file for vignette?

### ISSUE THREAD

**Issue by markbneal** [nlmixrdevelopment/nlmixr_bookdown#1]
In the vignettes chapter (https://github.com/nlmixrdevelopment/nlmixr_bookdown/blob/master/03-vignettes.Rmd), is there a dat file to run this line of code? 
`my2CptFit <- nlmixr(my2CptModel, dat, est="saem")`

**Comment by mattfidler** [comment]
Hi,

In `nlmixr2` all datasets are available in `nlmixr2data`.  It could include any 2 compartment model you wish.  However, this part of the vignette (though outdated) is simply meant to discuss the syntax and how to run `nlmixr`/`nlmixr2`
